n = input('Aperte uma tecla: ')
print(n.isalnum())
print(n.isalpha())
print(n.isascii())
print(n.isdigit())
print(n.islower())
print(n.isdecimal())
print(n.isidentifier())
print(n.isnumeric())
print(n.isspace())
print(n.isprintable())
print(n.istitle())
print(n.isupper())
print(n.__init_subclass__())
